name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Image
        run: docker build . --file Dockerfile --tag erstedigitalinnovations/meeting-app-backend
      -
        name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/meeting-app-backend
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull Docker Image
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull erstedigitalinnovations/meeting-app-backend
          host: ${{ secrets.SSH_HOST }}
          user: erste
          key: ${{ secrets.SSH_PKEY }}
      -
        name: Run docker image
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /meeting-app/meeting-app-backend
            docker-compose up -d
          host: ${{ secrets.SSH_HOST }}
          user: erste
          key: ${{ secrets.SSH_PKEY }}